error=TEST \!\!\!
user.already.on.follow.list = U¿ytkownik jest ju¿ na liœcie
user.success.add.to.follow.list = Uda³o siê dodaæ uzytkownika do œledzenia
error.on.add.user.to.follow.list = B³¹d przy próbie dodania u¿ytkownika
